const pyQuestions = [
  {
    question: 'What data do boolean operators return?',
    a: 'Integers',
    b: 'Float',
    c: 'String',
    d: 'True/False',
    answer: 'd',
  },
  {
    question: 'Who created python?',
    a: 'None of these',
    b: 'Guido van Rossum',
    c: 'Mark Zuckerberg',
    d: 'Aliens',
    answer: 'b',
  },
  {
    question: 'What is the lastest version of python (for year 2017)?',
    a: '4',
    b: '9',
    c: '2',
    d: '3',
    answer: 'd',
  },
  {
    question: 'Where is creator of python from?',
    a: 'USA',
    b: 'Mars',
    c: 'Netherland',
    d: 'Poland',
    answer: 'c',
  },
  {
    question: 'What sites from these are written in python?',
    a: 'YouTube',
    b: 'All of these',
    c: 'Google',
    d: 'Reddit',
    answer: 'b',
  },
  {
    question: 'Which of these is exponent operator?',
    a: '**',
    b: '/',
    c: '*',
    d: '%',
    answer: 'a',
  },
  {
    question: "What is n variable there: n = '5'?",
    a: 'String',
    b: 'Integer',
    c: 'Float',
    d: 'Tuple',
    answer: 'a',
  },
  {
    question: 'What is the difference between == and =?',
    a:
      '== compares whether two things are equal and = assigns a value to a variable',
    b:
      '== assigns a value to a variable and = compares whether two things are equal',
    c: 'both == and = can be used interchangeably',
    d: 'both == and = only assign values to variables',
    answer: 'a',
  },
  {
    question: 'What is symbol for writing a comment in Python?',
    a: '//',
    b: '#',
    c: '--',
    d: '~',
    answer: 'b',
  },
  {
    question: "Statement using 'and' operator results true if: ",
    a: 'Either of the operands is true',
    b: 'Both operands are false',
    c: 'Both operands are true',
    d: 'First operand is true',
    answer: 'c',
  },
]

export default pyQuestions
